# 服务端口
port: 8005
# 运行环境
env: dev
# 服务版本
version: 1.0.0
jwt_secret: ewerwerwerwerwer
database:
  # 数据库-主库
  driver: mysql
  dsn: root:123456@(127.0.0.1)/meadmin?charset=utf8&parseTime=True&loc=Local
  max_idle_conns: 10
  max_open_conns: 50
redis:
  net_work: tcp
  addr: 127.0.0.1
  prot: 6379
  password: ''
  prefix: ''